blueprint:
  id: ce2725b5259f44ebb38e54400faedd7f
  name: "MongoDB on VM"
  description: "Deploy a MongoDB replica set"
  services:
    primary:
      component:
        type: application
        name: mongodb
        role: primary
      constraints:
      - count: 1
    data:
      component:
        type: application
        name: mongodb
        role: data
      relations:
        primary: ssh
  options:
    domains:
      regex: ^(([a-zA-Z]|[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z]|[A-Za-z][A-Za-z0-9\-]*[A-Za-z0-9])$
      constrains:
      - setting: domain
        service: data
      - setting: domain
        service: primary
      description: 'The domain name to be used for the hostname of your server(s).'
      display-hints:
        group: database
        order: 1
      label: Domain
      sample: example.com
      type: string
      required: true
    server_count:
      label: Number of Servers
      type: integer
      required: true
      default: 2
      description: Number of Additional MongoDB servers (one will automatically be set as an arbiter).
      display-hints:
        group: server
        order: 1
      constraints:
      - greater-than-or-equal-to: 2
      constrains:
      - setting: count
        service: data
        resource_type: application
    region:
      label: Region
      type: string
      required: true
      default: ORD
      display-hints:
        group: deployment
        list-type: region
        choice:
        - DFW
        - ORD
        - LON
    os:
      label: Operating System
      description: The operating system for all of the servers.
      type: string
      default: Ubuntu 12.04
      display-hints:
        group: server
        order: 2
        list-type: compute.os
      choice:
      - Ubuntu 12.04
      - Ubuntu 12.10
      constraints:
      - in: ["Ubuntu 12.04", "Ubuntu 12.10"]
      constrains:
      - resource_type: compute
        service: data
        setting: os
      - setting: os
        service: primary
        resource_type: compute
    server_size:
      label: Server Size
      type: integer
      default: 512      
      description: The size of the instances in MB of RAM.
      display-hints:
        group: server
        order: 3
        list-type: compute.memory
        choice:
        - name: 512 Mb (20 Gb disk)
          value: 512
        - name: 1 Gb (40 Gb disk)
          value: 1024
        - name: 2 Gb (80 Gb disk)
          value: 2048
        - name: 4 Gb (160 Gb disk)
          value: 4096
        - name: 8 Gb (320 Gb disk)
          value: 8192
        - name: 16 Gb (620 Gb disk)
          value: 15872
        - name: 30 Gb (1.2 Tb disk)
          value: 30720
      constrains:
      - resource_type: compute
        service: data
        setting: memory
      - resource_type: compute
        service: primary
        setting: memory
  meta-data:
    application-name: MongoDB Replicaset
    blueprint-type: Component
    flavor: Multi-Server
    reach-info:
      icon-20x20: https://600861890ddb34a8670a-744765205721eed93c384dae790e86aa.ssl.cf2.rackcdn.com/mongodb-icon-20x20.png
      tattoo: https://600861890ddb34a8670a-744765205721eed93c384dae790e86aa.ssl.cf2.rackcdn.com/mongodb-tattoo.png
      groups: ["Servers", "Database"]
environment:
  description: This environment uses next-gen cloud servers.
  name: Next-Gen Open Cloud
  providers:
    chef-solo:
      vendor: opscode
      constraints:
      - source: %repo_url%
    nova: {}
    common:
      vendor: rackspace
inputs:
  blueprint:
    region: ORD
    server_size: 1024
    domains: example.com
