blueprint:
  id: ce2725b5259f44ebb38e54400faedd7f
  name: "MongoDB on VM"
  version: 1.0.1
  description: "Deploy a MongoDB replica set"
  services:
    primary:
      component:
        type: application
        name: mongodb
        role: primary
      constraints:
      - count: 1
    data:
      component:
        type: application
        name: mongodb
        role: data
      relations:
        primary: ssh
  options:
    domains:
      constrains:
      - setting: domain
        service: data
      - setting: domain
        service: primary
      description: 'The domain name to be used for the hostname of your server(s).'
      help: |
        **Required**: The domain provided will be used for setting the hostnames of your servers.
      display-hints:
        group: database
        order: 1
        sample: example.com
      label: Domain
      type: string
      required: true
      constraints:
      - regex: ^(([a-zA-Z]|[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z]|[A-Za-z][A-Za-z0-9\-]*[A-Za-z0-9])$
    server_count:
      label: Additional Nodes
      type: integer
      required: true
      default: 2
      description: Number of Additional MongoDB servers (one will automatically be set as an arbiter).
      help: |
        **Required**: The number of additional nodes to include in addition to the master node.
      display-hints:
        group: server
        order: 1
      constraints:
      - greater-than-or-equal-to: 2
        message: must include two or more servers
      - less-than-or-equal-to: 11
        message: must be fewer than 12 servers 
      constrains:
      - setting: count
        service: data
        resource_type: application
    region:
      label: Region
      type: string
      required: true
      default: ORD
      display-hints:
        group: deployment
        list-type: region
        choice:
        - DFW
        - ORD
        - LON
        - SYD
    os:
      label: Operating System
      description: The operating system for all of the servers.
      type: string
      default: Ubuntu 12.04
      display-hints:
        group: server
        order: 2
        list-type: compute.os
        choice:
        - name: Ubuntu 12.04 LTS (Precise Pangolin)
          value: Ubuntu 12.04
        - name: Ubuntu 12.10 (Quantal Quetzal)
          value: Ubuntu 12.10
      constraints:
      - in: ["Ubuntu 12.04", "Ubuntu 12.10"]
      constrains:
      - resource_type: compute
        service: data
        setting: os
      - setting: os
        service: primary
        resource_type: compute
    server_size:
      label: Server Size
      type: integer
      default: 512      
      description: The size of the instances in MB of RAM.
      display-hints:
        group: server
        order: 3
        list-type: compute.memory
        choice:
        - name: 512 MB (20 GB disk)
          value: 512
        - name: 1 GB (40 GB disk)
          value: 1024
        - name: 2 GB (80 GB disk)
          value: 2048
        - name: 4 GB (160 GB disk)
          value: 4096
        - name: 8 GB (320 GB disk)
          value: 8192
        - name: 15 GB (620 GB disk)
          value: 15000
        - name: 30 GB (1.2 TB disk)
          value: 30720
      constrains:
      - resource_type: compute
        service: data
        setting: memory
      - resource_type: compute
        service: primary
        setting: memory
  meta-data:
    schema-version: v0.7
    application-name: MongoDB
    blueprint-type: Component
    flavor: Multiple Linux servers with a MongoDB 2.4.4 Replica Set
    flavor-weight: 1
    reach-info:
      icon-20x20: https://600861890ddb34a8670a-744765205721eed93c384dae790e86aa.ssl.cf2.rackcdn.com/mongodb-icon-20x20.png
      tattoo: https://600861890ddb34a8670a-744765205721eed93c384dae790e86aa.ssl.cf2.rackcdn.com/mongodb-tattoo.png
      option-groups:
      - server: Server Options
      - database: Database Options
  documentation:
    abstract: |
      Multiple Linux servers with [MongoDB 2.4.4](http://www.mongodb.org/).  
      By default, one server will be set as master, the second server will be the arbiter, the remaining servers
      will be slave nodes with a maximum of 12 total members. 
    instructions: |
      #### Getting Started
      
      If you're new to MongoDB, check out the 
      [Getting Started with MongoDB](http://docs.mongodb.org/manual/tutorial/getting-started/) 
      guide.  This document covers the basics of connecting to and using your new replica set.
  display-outputs:
    "Server Private Key":
      type: private-key
      source: "resources://deployment-keys/instance/private_key"
      group: application
      is-secret: true
      order: 1
environment:
  description: This environment uses next-gen cloud servers.
  name: Next-Gen Open Cloud
  providers:
    chef-solo:
      vendor: opscode
      constraints:
      - source: %repo_url%
    nova: {}
    common:
      vendor: rackspace
inputs:
  blueprint:
    region: ORD
    server_size: 1024
    server_count: 2
    domains: example.com
