blueprint:
  name: "MongoDB on VM"
  description: "Deploy a MongoDB replica set"
  services:
    primary:
      component:
        type: application
        name: mongodb
        role: primary
      constraints:
      - count: 1
    data:
      component:
        type: application
        name: mongodb
        role: data
      relations:
        primary: ssh
  options:
    domains:
      regex: ^(([a-zA-Z]|[a-zA-Z][a-zA-Z0-9\-]*[a-zA-Z0-9])\.)*([A-Za-z]|[A-Za-z][A-Za-z0-9\-]*[A-Za-z0-9])$
      constrains:
      - setting: domain
        service: data
      - setting: domain
        service: primary
      description: 'The domain name to be used for the hostname of your server(s).'
      label: Domain
      sample: example.com
      type: string
      required: true
    username:
      required: true
      type: string
      default: admin
      label: Username
      description: MongoDB admin username.
    password:
      required: true
      type: password
      default: =generate_password()
      label: Password
      description: MongoDB admin password.
    server_count:
      required: true
      type: int
      default: 2 
      description: Number of Additional MongoDB data nodes.
      label: Data Nodes
      constrains:
      - setting: count
        service: data
        resource_type: application
    region:
      required: true
      type: select
      default: ORD
      label: Region
      choice:
      - DFW
      - ORD
      - LON
    os:
      constrains:
      - setting: os
        service: data
        resource_type: compute
      - setting: os
        service: primary
        resource_type: compute
      description: The operating system for the all servers.
      default: Ubuntu 12.04
      label: Operating System
      type: select
      choice:
      - Ubuntu 12.04
      - Ubuntu 12.10
    server_size:
      constrains:
      - setting: memory
        service: data
        resource_type: compute
      - setting: memory
        service: primary
        resource_type: compute
      description: The size of the database instances in MB of RAM.
      default: 512
      label: Server Size
      type: select
      choice:
      - name: 512 Mb
        value: 512
      - name: 1 Gb
        value: 1024
      - name: 2 Gb
        value: 2048
      - name: 4 Gb
        value: 4096
      - name: 8 Gb
        value: 8092
      - name: 16 Gb
        value: 16384
      - name: 30 Gb
        value: 30720
environment:
  description: This environment uses next-gen cloud servers.
  name: Next-Gen Open Cloud
  providers:
    chef-solo:
      vendor: opscode
      constraints:
      - source: %repo_url%
    nova: {}
    common:
      vendor: rackspace
inputs:
  blueprint:
    region: ORD
    server_size: 1024
    domains: example.com
